//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTable
    {
        public int billID { get; set; }
        public string sellerName { get; set; }
        public string billDate { get; set; }
        public int totalAmount { get; set; }
    }
}
