//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerTable
    {
        public int managerID { get; set; }
        public string managerName { get; set; }
        public int managerAge { get; set; }
        public string managerPhone { get; set; }
        public string managerAddress { get; set; }
        public string managerPassword { get; set; }
    }
}
